---
- name: Deploy infra
  hosts: all
  gather_facts: false
  tasks:
    - name: "Create VMs"
      register: createvm
      delegate_to: 127.0.0.1
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_username }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        proxmox_default_behavior: no_defaults
        clone: "{{ proxmox_image }}"
        name: "{{ hostname }}"
        node: "{{ proxmox_node }}"
        full: no
        timeout: 300

    - name: Let the new vm settle
      pause:
        seconds: 10
      when: createvm is changed

    - name: "Add/Update NIC net0"
      delegate_to: 127.0.0.1
      community.general.proxmox_nic:
        api_user: "{{ proxmox_username }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        name: "{{ hostname }}"
        interface: "net0"
        bridge: "{{ proxmox_bridge }}"

    - name: "Update VM parameters"
      register: updatevm
      delegate_to: 127.0.0.1
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_username }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        name: "{{ hostname }}"
        node: "{{ proxmox_node }}"
        ipconfig:
          ipconfig0: "ip={{ ip_address }}/24,gw=172.16.0.1"
        nameservers:
          - "172.16.0.1"
        searchdomains: 'syntax.sv'
        ciuser: "{{ ci_username }}"
        cipassword: "{{ ci_password }}"
        sshkeys: "{{ ci_sshkey }}"
        scsi:
          scsi0: 'local-lvm:10'
          scsi1: 'local-lvm:cloudinit,format=qcow2'
        proxmox_default_behavior: no_defaults
        acpi: yes
        autostart: no
        balloon: 0
        boot: c
        cpu: kvm64
        sockets: "{{ sockets }}"
        cores: "{{ cores }}"
        memory: "{{ mem }}"
        force: no
        kvm: yes
        onboot: yes
        ostype: l26
        tablet: no
        template: no
        vga: std
        update: yes
      when: createvm is changed

    - name: "Start VMs"
      delegate_to: 127.0.0.1
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_username }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        proxmox_default_behavior: no_defaults
        node: "{{ proxmox_node }}"
        name: "{{ hostname }}"
        state: started

    - name: "Wait for VM's to start"
      delegate_to: localhost
      wait_for:
        host: "{{ ip_address }}"
        port: 22
        delay: 10
        search_regex: OpenSSH
      when: createvm is changed

- name: Final configuration taks for new hosts
  become: true
  hosts: all
  tasks:
    - name: 'Disable cloud-init'
      copy:
        dest: '/etc/cloud/cloud-init.disabled'
        content: 'disabled by ansible\n'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"